title: Maciej Jankowski
description: >-
  Personal website, blog, and portfolio of Maciej Jankowski. Thoughts, projects, and resources on technology, creativity, and self-development.
author: Maciej Jankowski
baseurl: ""
url: ""
permalink: pretty
